### ISSUE TITLE
튜토리얼에서 총알 정의 부분이 빠져있습니다.

### ISSUE THREAD

**Issue by raveneer** [jhjjgu0115/RimWorldModGuide#2]
`<defName>PlagueGun</defName>`
...
에서 
`<defaultProjectile>PlagueGun_Bullet</defaultProjectile>`

이 부분을 수정하라는 설명이 빠져 있어서 추가해준 총알이 아니라 기본 총알을 발사하게 됩니다.

**Comment by solaris0115** [comment]
해당항목 수정에 대해서 코멘트를 추가로 달아놨습니다.
