### ISSUE TITLE
역병총 가이드에서 한글 출력이 제대로 되지 않습니다.

### ISSUE THREAD

**Issue by raveneer** [jhjjgu0115/RimWorldModGuide#3]
![image](https://user-images.githubusercontent.com/19799411/82201164-e6f21880-993a-11ea-822a-6e44c761cd2e.png)

예제를 따라했는데 한글 대신 영어로만 출력이 됩니다.

Korean (한국어) 대신 Korean 으로 폴더명을 써도 동일한 현상이 있습니다.

`                    Messages.Message("TST_PlagueBullet_SuccessMessage".Translate(this.launcher.Label, hitPawn.Label )
                        , MessageTypeDefOf.NeutralEvent);`

번역 api가 변경되서 변경된 쪽으로 수정하여 빌드했습니다.

림월드를 새로 설치하고 역병총 모드만 켠 상태이고요.

영어의 xml 이 제대로 출력되는 걸로 봐서는 폴더 설정 문제인가 싶긴 한데 정확한 원인을 모르겠네요.

림월드 버젼은 1.1 입니다. 

[PlagueGun.zip](https://github.com/solaris0115/RimWorldModGuide/files/4643466/PlagueGun.zip)

**Comment by solaris0115** [comment]
1.0 또는 0.18이전 빌드에서 작성된 가이드라 1.1 버전에 맞춰 업데이트를 할 예정입니다.
